# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' stagewise lasso 
#' 
#' @param X predictor matrix 
#' @param y response vector 
#' @param eps stepsize 
#' @param tol tolanrance paramater 
#' @param max_iteration maximum iteration number 
#' @return A list consists of 
#' \item{beta_path}{the solution path of beta}
#' \item{lambda_path}{the path of lambda} 
#' \item{sigma2_path}{the path of estimated variance via maximum likelihood estimation}
#' @export 
#' @aliases blasso 
blasso <- function(X, y, eps, tol, max_iteration) {
    .Call('_lassoPath_blasso', PACKAGE = 'lassoPath', X, y, eps, tol, max_iteration)
}

#' coordinate descent algorithm for lasso
#'
#' @param X predictor matrix
#' @param y response vector
#' @param lambda penalty parameter
#' @param max_iteration maximum iteration number
#' @param tol tolanrance parameter
#' @return hat_beta lasso estimation with lambda
#' @export 
#' @aliases codelasso 
codelasso <- function(X, y, lambda, max_iteration, tol) {
    .Call('_lassoPath_codelasso', PACKAGE = 'lassoPath', X, y, lambda, max_iteration, tol)
}

#' lasso solution path via coordinate descent algorithm 
#' @param X predictor matrix 
#' @param y response vector 
#' @param nlambda the number of penalty parameter 
#' @param max_iteration maximum iteration number 
#' @param tol tolanrance parameter 
#' @param min_lambda minimum lambda 
#' @return A list consists of 
#' \item{beta_path}{the solution path of beta} 
#' \item{lambda_path}{the lambda path} 
#' \item{sigma2_path}{the path of estimated variance via maximum likelihood estimation}
#' @export 
#' @aliases codelasso_path 
codelasso_path <- function(X, y, nlambda, max_iteration, tol, min_lambda) {
    .Call('_lassoPath_codelasso_path', PACKAGE = 'lassoPath', X, y, nlambda, max_iteration, tol, min_lambda)
}

