// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// blasso
Rcpp::List blasso(arma::mat& X, arma::mat& y, double eps, double tol, unsigned max_iteration);
RcppExport SEXP _lassoPath_blasso(SEXP XSEXP, SEXP ySEXP, SEXP epsSEXP, SEXP tolSEXP, SEXP max_iterationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< unsigned >::type max_iteration(max_iterationSEXP);
    rcpp_result_gen = Rcpp::wrap(blasso(X, y, eps, tol, max_iteration));
    return rcpp_result_gen;
END_RCPP
}
// codelasso
arma::vec codelasso(arma::mat& X, arma::vec& y, arma::vec& hat_beta, double lambda, unsigned max_iteration, double tol);
RcppExport SEXP _lassoPath_codelasso(SEXP XSEXP, SEXP ySEXP, SEXP hat_betaSEXP, SEXP lambdaSEXP, SEXP max_iterationSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type hat_beta(hat_betaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< unsigned >::type max_iteration(max_iterationSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(codelasso(X, y, hat_beta, lambda, max_iteration, tol));
    return rcpp_result_gen;
END_RCPP
}
// codelasso_path
Rcpp::List codelasso_path(arma::mat& X, arma::vec& y, unsigned nlambda, unsigned max_iteration, double tol, double min_lambda);
RcppExport SEXP _lassoPath_codelasso_path(SEXP XSEXP, SEXP ySEXP, SEXP nlambdaSEXP, SEXP max_iterationSEXP, SEXP tolSEXP, SEXP min_lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< unsigned >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< unsigned >::type max_iteration(max_iterationSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type min_lambda(min_lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(codelasso_path(X, y, nlambda, max_iteration, tol, min_lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lassoPath_blasso", (DL_FUNC) &_lassoPath_blasso, 5},
    {"_lassoPath_codelasso", (DL_FUNC) &_lassoPath_codelasso, 6},
    {"_lassoPath_codelasso_path", (DL_FUNC) &_lassoPath_codelasso_path, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_lassoPath(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
